Thank you ChatGPT.

I ran: (chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ pip install git+git://github.com/rhasspy/piper-tts.git
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+git://github.com/rhasspy/piper-tts.git
  Cloning git://github.com/rhasspy/piper-tts.git to /tmp/pip-req-build-y9algfkh
  Running command git clone --filter=blob:none --quiet git://github.com/rhasspy/piper-tts.git /tmp/pip-req-build-y9algfkh
  fatal: unable to connect to github.com:
  github.com[0: 4.237.22.38]: errno=Connection timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/rhasspy/piper-tts.git /tmp/pip-req-build-y9algfkh did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/rhasspy/piper-tts.git /tmp/pip-req-build-y9algfkh did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ 

How can I generate a Personal Access Token (PAT) from GitHub?

How can we fix this once and for all?
