Thank you ChatGPT. You are great.

I had a en_US-amy-low.json file just containing the words "Entry not found". I copied the correct en_US-amy-low.onnx.json file to my voices/en_US-amy-low folder.

I ran (chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ cat voices/en_US-amy-low/en_US-amy-low.onnx.json | head -n 10
{
  "audio": {
    "sample_rate": 16000,
    "quality": "low"
  },
  "espeak": {
    "voice": "en-us"
  },
  "inference": {
    "noise_scale": 0.667,
(chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ 

I am confident this is what has been causing the problem all along.

I modified my test_tts.py file as follows:

test_tts.py
import subprocess

VOICE = "/home/nickspi5/Chatty_AI/voices/en_US-amy-low/en_US-amy-low.onnx"
CONFIG = "/home/nickspi5/Chatty_AI/voices/en_US-amy-low/en_US-amy-low.onnx.json"
TEXT = "Hello Nick, this is a test of Piper text to speech on your Raspberry Pi 5"
OUTPUT = "output.wav"

# Run Piper
command = [
    "./piper/piper",
    "--model", VOICE,
    "--config", CONFIG,
    "--output_file", OUTPUT
]

subprocess.run(command, input=TEXT.encode("utf-8"))

I then ran (chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ python3 test_tts.py
[2025-07-18 16:02:58.215] [piper] [info] Loaded voice in 0.988800676 second(s)
[2025-07-18 16:02:58.216] [piper] [info] Initialized piper
output.wav
[2025-07-18 16:02:58.719] [piper] [info] Real-time factor: 0.09808212677444794 (infer=0.497472547 sec, audio=5.072 sec)
[2025-07-18 16:02:58.719] [piper] [info] Terminated piper
(chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ aplay output.wav
Playing WAVE 'output.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
(chatty-venv) nickspi5@raspberrypi1:~/Chatty_AI $ 

Everything is now running perfectly and I am very happy with the outcome.


